apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prod-user-role
  namespace: prod
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
