apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guu-band-dev
spec:
  project: default
  source:
    repoURL: https://github.com/polfor/guu.band_config.git
    path: overlays/dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
