apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: prod-cpu-stress
  namespace: chaos-mesh
spec:
  mode: all
  selector:
    namespaces:
      - prod
  stressors:
    cpu:
      workers: 2
      load: 75
